id: AA52E0393
title: CI_Pāyantika 37
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:31:55.329329
  last_modified_at: 2022-03-01 22:31:55.329332
