id: AA52E0393
title: CI_Naiḥsargika 15
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:31:55.242108
  last_modified_at: 2022-03-01 22:31:55.242112
