id: AA52E0393
title: CI_Naiḥsargika 28
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:31:55.262417
  last_modified_at: 2022-03-01 22:31:55.262420
